spring:
  application:
    name: first-come-first-served

  datasource:
    url: jdbc:mysql://localhost:3306/myapp?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: myuser
    password: mypass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  cloud:
    stream:
      bindings:
        coupon-out-0:
          destination: first-come-system
        coupon-in-0:
          destination: first-come-system
          group: coupon-group
      kafka:
        binder:
          brokers: localhost:9092,localhost:9093,localhost:9094